### ISSUE TITLE
Travis failure?

### ISSUE THREAD

**Issue by FranklinChen** [supki/guard-haskell#6]
I'm curious whether this project is being maintained. I noticed that there is a Travis failure.

**Comment by supki** [comment]
Hey!

Yeah, I maintain it. Haven't had the need to fix much lately since it works for me as it is. Please, feel free to open an issue if you're having any problems.

The build failure is from the experiments with the UI I ran last year. I probably should flesh them out and push the release, just haven't got around to it yet. For the time being, stick to `guard-haskell-2.0` if you'd like to try it out. (The relevant [README][0] file describes what should go into `Gemfile` for `bundle exec guard` to download the correct `guard-haskell` version)

  [0]: https://github.com/supki/guard-haskell/tree/2.0.1#gemfile

**Comment by FranklinChen** [comment]
Thanks for the fix. I tried out this tool and it seems to work pretty well.
